apiVersion: v1
kind: Service
metadata:
  labels:
    name: rabbitmq
  name: rabbitmq
spec:
  ports:
    - port: 5672
      protocol : TCP
      name : default
  selector:
    type: rmq-node
  type : NodePort
