apiVersion: v1
kind: Service
metadata:
  labels:
    name: rmq-node-1-svc
  name: rmq-node-1-svc
spec:
  ports:
    - port: 4369
      protocol : TCP
      name : epmd-port
    - port: 25672
      protocol : TCP
      name : dist-port
  selector:
    name: rmq-node-1

